### ISSUE TITLE
大佬，能不能提供arm64的支持

### ISSUE THREAD

**Issue by darkelfzdy** [amuluze/amprobe#1]
大佬，能不能提供arm64的支持？我看到docker只支持x86

**Comment by amuluze** [comment]
收到，我找个环境试试

**Comment by chaomarks** [comment]
感谢大佬，需要一个arm64的，如果有的话赞助你，希望你能干掉portainer

**Comment by amuluze** [comment]
> 大佬，能不能提供arm64的支持？我看到docker只支持x86

有 arm64 的镜像啦，可以通过 docker pull amuluze/amprobe_arm:v1.3.2 获取，或者从 release 出下载镜像压缩包 docker load -i amprobe.arm.tar.gz

**Comment by chaomarks** [comment]
支持过了，不过我还没用，以为正在被一个
docker pull镜像时的这个错误所困扰，机器有点差劲
error pulling image configuration: download failed after attempts=6: tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-04-24T23:49:04+08:00 is after 2021-09-30T14:01:15Z

**Comment by amuluze** [comment]
> 支持过了，不过我还没用，以为正在被一个 docker pull镜像时的这个错误所困扰，机器有点差劲 error pulling image configuration: download failed after attempts=6: tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-04-24T23:49:04+08:00 is after 2021-09-30T14:01:15Z

![1](https://github.com/amuluze/amprobe/assets/16292237/1b9e77d4-1c8f-4a36-bf76-9a07f78cea79)
![2](https://github.com/amuluze/amprobe/assets/16292237/fdb9aeb6-86a4-467a-962d-f4a79a704eeb)
可以从这里下载上传到服务器，docker load -i amprobe.arm.tar.gz
