### ISSUE TITLE
arm架构的机器，同样的命令，1.3.2可以，1.3.3用不了

### ISSUE THREAD

**Issue by chaomarks** [amuluze/amprobe#10]
docker run命令如下
docker run -itd --name amprobe \
--restart=always \
--net=bridge \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-v /sata/docker/amprobe/proc:/host/proc:ro \
	-v /sata/docker/amprobe/sys:/host/sys:ro \
	-v /sata/docker/amprobe/dev:/host/dev:ro \
	-v /sata/docker/amprobe/etc:/host/etc:ro \
	-v /sata/docker/amprobe/:/rootfs:ro \
	-v /sata/docker/amprobe/data/amprobe/configs:/app/configs \
	-p 10010:80 \
	amuluze/amprobe_arm:v1.3.2

**Comment by chaomarks** [comment]
![image](https://github.com/amuluze/amprobe/assets/93130581/51c72238-4dc6-40b8-9520-e4d56a28a204)
这块往下拉一下吗，看着太空白

**Comment by amuluze** [comment]
> ![image](https://private-user-images.githubusercontent.com/93130581/327658217-51c72238-4dc6-40b8-9520-e4d56a28a204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3OTU0NTUsIm5iZiI6MTcxNDc5NTE1NSwicGF0aCI6Ii85MzEzMDU4MS8zMjc2NTgyMTctNTFjNzIyMzgtNGRjNi00MGI4LTk1MjAtZTRkNTZhMjhhMjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDAzNTkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkN2JhNTVmODQ2YzcyYjBjZTcwOWI0MzY3YWRkZjNlM2VkNjBlZWFkZjNlOTMwZDdjYTg2YWY4Yzk2MTdhYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HyytIAeUWWbJTeeiQi5TWkZeOzXRX-qFnWr5NWRgYsA) 这块往下拉一下吗，看着太空白

好的，收到，后续我调整一下

**Comment by amuluze** [comment]
> docker run命令如下 docker run -itd --name amprobe --restart=always --net=bridge -v /var/run/docker.sock:/var/run/docker.sock -v /sata/docker/amprobe/proc:/host/proc:ro -v /sata/docker/amprobe/sys:/host/sys:ro -v /sata/docker/amprobe/dev:/host/dev:ro -v /sata/docker/amprobe/etc:/host/etc:ro -v /sata/docker/amprobe/:/rootfs:ro -v /sata/docker/amprobe/data/amprobe/configs:/app/configs -p 10010:80 amuluze/amprobe_arm:v1.3.2

v1.3.3 用不了是指怎么个用不了啊，能具体说下吗，我在 arm 版 Ubuntu 22.04 环境下测试可用，另外用 --net=bridge 参数的话，磁盘和流量监控会有一些问题的

**Comment by chaomarks** [comment]
能打开页面登录时显示服务器错误，因为80端口用不了所以host模式用不了，希望可以把容器web端口改成其他的

**Comment by amuluze** [comment]
> 能打开页面登录后页面显示服务器错误，因为80端口用不了所以host模式用不了，希望可以把容器web端口改成其他的我试试host模式

https://amprobedoc.amuluze.com/views/faq.html#_80-%E7%AB%AF%E5%8F%A3%E8%A2%AB%E5%8D%A0%E7%94%A8%E4%BA%86%E6%80%8E%E4%B9%88%E5%8A%9E 可以通过挂载 Nginx 配置来修改默认的端口
