### ISSUE TITLE
部署之后无法正常打开登录页面

### ISSUE THREAD

**Issue by godway111** [amuluze/amprobe#14]
![image](https://github.com/amuluze/amprobe/assets/103880643/7b480118-6389-47cc-b8f8-adc4aa69f607)
![image](https://github.com/amuluze/amprobe/assets/103880643/4197bc49-e5df-4e72-894e-39434a7e3c5d)
![image](https://github.com/amuluze/amprobe/assets/103880643/09c3c9bc-8cc6-40d9-8dfe-aff00f887095)
![image](https://github.com/amuluze/amprobe/assets/103880643/03b384b9-b6ac-4022-879a-be7ff2dace12)

**Comment by amuluze** [comment]
> ![image](https://private-user-images.githubusercontent.com/103880643/330360270-7b480118-6389-47cc-b8f8-adc4aa69f607.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzYwNjUsIm5iZiI6MTcxNTg3NTc2NSwicGF0aCI6Ii8xMDM4ODA2NDMvMzMwMzYwMjcwLTdiNDgwMTE4LTYzODktNDdjYy1iOGY4LWFkYzRhYTY5ZjYwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxNjA5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmVjY2FiMTg5YWQwNDFiNTIwOWE1ZTQ4NGZlYzkyZGZhMTUzYjM4NzBkZWE5ZDM3YjcwYzU4MzkxMTNjMjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tP-jovrlC7yu-axjcNCN0OThSmwRBKDGP1Yc_9okAK0) ![image](https://private-user-images.githubusercontent.com/103880643/330360400-4197bc49-e5df-4e72-894e-39434a7e3c5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzYwNjUsIm5iZiI6MTcxNTg3NTc2NSwicGF0aCI6Ii8xMDM4ODA2NDMvMzMwMzYwNDAwLTQxOTdiYzQ5LWU1ZGYtNGU3Mi04OTRlLTM5NDM0YTdlM2M1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxNjA5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzQxM2Y3N2FjODEzYmUzOWJkZjEwMWY4YzU5MWQ2MWZhYWE4ZjM3NGEwZTFlZDQxZTUzZjUxYzg3MjYxMjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p8sRmxzE_54uwYZgbCBxjd6Gw0ip-9ey2HQSVBwWeX4) ![image](https://private-user-images.githubusercontent.com/103880643/330360529-09c3c9bc-8cc6-40d9-8dfe-aff00f887095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzYwNjUsIm5iZiI6MTcxNTg3NTc2NSwicGF0aCI6Ii8xMDM4ODA2NDMvMzMwMzYwNTI5LTA5YzNjOWJjLThjYzYtNDBkOS04ZGZlLWFmZjAwZjg4NzA5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxNjA5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWJhZjNkYjk3NGM2ZmYyZWVmZmRlMGYwYzViNDE3ZjM0OTZiMDY3ZmViNzE0NGI1YTY0MThmMmQ2MzU3MDM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eKuzKpqFtDulAfuYOifetiGe_XJr9mqO1is4il-R7Ak) ![image](https://private-user-images.githubusercontent.com/103880643/330360782-03b384b9-b6ac-4022-879a-be7ff2dace12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzYwNjUsIm5iZiI6MTcxNTg3NTc2NSwicGF0aCI6Ii8xMDM4ODA2NDMvMzMwMzYwNzgyLTAzYjM4NGI5LWI2YWMtNDAyMi04NzlhLWJlN2ZmMmRhY2UxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxNjA5MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjVjMjRlNzliODliMTMwMjQzZDU3MDg4NTI2MGI0M2U5YjIwYWM1ZGJlNGRlNzM0MWI3ZTI0NmRlOTA3NTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NvdWkWa3TXQKxmlLEZdwm4we6wZa1ft4FK2Pz7MneJU)

docker 版本须 >= 20.10.9

**Comment by docker-master** [comment]
等一会就好了，不过我受不了了，我这暴脾气，删掉
