### ISSUE TITLE
不支持arm平台吗

### ISSUE THREAD

**Issue by ksi1110** [amuluze/amprobe#16]
![image](https://github.com/amuluze/amprobe/assets/18417132/8e688082-3832-43aa-97af-421eedb04940)

希望可以支持arm平台

**Comment by amuluze** [comment]
> ![image](https://private-user-images.githubusercontent.com/18417132/331447153-8e688082-3832-43aa-97af-421eedb04940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODY0NjksIm5iZiI6MTcxNjE4NjE2OSwicGF0aCI6Ii8xODQxNzEzMi8zMzE0NDcxNTMtOGU2ODgwODItMzgzMi00M2FhLTk3YWYtNDIxZWVkYjA0OTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2MjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NTJlOTM4ZmM0MTQ2MjRkYmJmMTgwYTlkZjc3MGI3NmY4ZDZlNDQxN2Q3NGE5NmQ5ODIxMzk3OWE5NzgzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XGXDG3EN-adCvg4898jEKorgfdeu6zpM5SFaDP1Smps)
> 
> 希望可以支持arm平台

![image](https://github.com/amuluze/amprobe/assets/16292237/bea9dca7-99cd-4998-92b1-e6163b053117)

支持的，可以从这下载 arm 的镜像，上传后 docker load -i amprobe.arm.tar.gz 导入镜像，镜像名称为： amuluze/amprobe_arm:v1.3.3

**Comment by ksi1110** [comment]
> > ![image](https://private-user-images.githubusercontent.com/18417132/331447153-8e688082-3832-43aa-97af-421eedb04940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODY0NjksIm5iZiI6MTcxNjE4NjE2OSwicGF0aCI6Ii8xODQxNzEzMi8zMzE0NDcxNTMtOGU2ODgwODItMzgzMi00M2FhLTk3YWYtNDIxZWVkYjA0OTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2MjI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NTJlOTM4ZmM0MTQ2MjRkYmJmMTgwYTlkZjc3MGI3NmY4ZDZlNDQxN2Q3NGE5NmQ5ODIxMzk3OWE5NzgzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XGXDG3EN-adCvg4898jEKorgfdeu6zpM5SFaDP1Smps)
> > 希望可以支持arm平台
> 
> ![image](https://private-user-images.githubusercontent.com/16292237/331963764-bea9dca7-99cd-4998-92b1-e6163b053117.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzI5NDgsIm5iZiI6MTcxNjUzMjY0OCwicGF0aCI6Ii8xNjI5MjIzNy8zMzE5NjM3NjQtYmVhOWRjYTctOTljZC00OTk4LTkyYjEtZTYxNjNiMDUzMTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA2MzcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMDk3YTYyZjhjMDBhZGQ4YzZjYzYzM2NmMmYyM2I2ZTJmNjJiNGNiZDBhODEwZjE5NzZiMWQyYmE3NjcyZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.byIOCcdFzHJ5MqqLye-jTKPcwvLSZ7d_BycMEdni5Jg)
> 
> 支持的，可以从这下载 arm 的镜像，上传后 docker load -i amprobe.arm.tar.gz 导入镜像，镜像名称为： amuluze/amprobe_arm:v1.3.3

感谢回复哦，我部署试试看，抱歉看到晚了
