### ISSUE TITLE
官网使用手册无法打开

### ISSUE THREAD

**Issue by charley008** [amuluze/amprobe#22]
https://amprobe.amuluze.com/官网上有一个使用手册。点击进去一直没反应，然后发现跳转到了https://amprobe.amuluze.com/doc 应该是proxy_pass 没有设置好。不一会卡在http://amprobe.amuluze.com:8083/doc/这里，然后导致无法访问。
​其实链接应该是https://amprobe.amuluze.com/doc/ 多一个“/”才能正常访问。

**Comment by amuluze** [comment]
> [https://amprobe.amuluze.com/官网上有一个使用手册。点击进去一直没反应，然后发现跳转到了https://amprobe.amuluze.com/doc](https://amprobe.amuluze.com/%E5%AE%98%E7%BD%91%E4%B8%8A%E6%9C%89%E4%B8%80%E4%B8%AA%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C%E3%80%82%E7%82%B9%E5%87%BB%E8%BF%9B%E5%8E%BB%E4%B8%80%E7%9B%B4%E6%B2%A1%E5%8F%8D%E5%BA%94%EF%BC%8C%E7%84%B6%E5%90%8E%E5%8F%91%E7%8E%B0%E8%B7%B3%E8%BD%AC%E5%88%B0%E4%BA%86https://amprobe.amuluze.com/doc) 应该是proxy_pass 没有设置好。不一会卡在[http://amprobe.amuluze.com:8083/doc/这里，然后导致无法访问。](http://amprobe.amuluze.com:8083/doc/%E8%BF%99%E9%87%8C%EF%BC%8C%E7%84%B6%E5%90%8E%E5%AF%BC%E8%87%B4%E6%97%A0%E6%B3%95%E8%AE%BF%E9%97%AE%E3%80%82)​其实链接应该是https://amprobe.amuluze.com/doc/ 多一个“/”才能正常访问。

收到，已更正，感谢老铁
