### ISSUE TITLE
Deployment was attempted, but the configuration and version information were empty.

### ISSUE THREAD

**Issue by 314767251** [amuluze/amprobe#25]
![image](https://github.com/user-attachments/assets/957ebacd-0d0d-4a70-8fe7-3c7117ebb6aa)
Is this related to the glibc version?

Are there any deployment documents for reference?

**Comment by amuluze** [comment]
There is no dependency with glibc.
Which OS version are you using?

**Comment by amuluze** [comment]
> ![image](https://private-user-images.githubusercontent.com/63150035/354150169-957ebacd-0d0d-4a70-8fe7-3c7117ebb6aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDk0NjEsIm5iZiI6MTcyMjUwOTE2MSwicGF0aCI6Ii82MzE1MDAzNS8zNTQxNTAxNjktOTU3ZWJhY2QtMGQwZC00YTcwLThmZTctM2M3MTE3ZWJiNmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEwNDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYWVhNGY1MjIzM2FhMGQyNDE3Zjc1ZDc4NDJkZGU1YTgxOTQwZGFiYjQyNWNhZDBjYWRiOTg2ZThjYzZhNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2pro77dcRuzSeGEh-7pKkCISc4RxQ_92R2XP-UUC_Hw) Is this related to the glibc version?
> 
> Are there any deployment documents for reference?

deployment documents: https://amprobe.amuluze.com/doc/v1.3.5/docker.html

**Comment by 314767251** [comment]
3Q

**Comment by 314767251** [comment]
好像环境还需要安装docker-compose 工具？

**Comment by 314767251** [comment]
Should the deployment environment also need to install docker-compose?

**Comment by 314767251** [comment]
> There is no dependency with glibc. Which OS version are you using?

[root@jimv47 dm8]# ./installer.bin 
[file list]: "amvector.install"
[file list]: "setup.sh"
[file list]: "VERSION.TXT"
[file] Extracting amvector.install...
[file] Extracting setup.sh...
[file] Extracting VERSION.TXT...
[docker_image] Loaded image: amuluze/amprobe:v1.3.5
[shell] Running command: ./setup.sh
+ '[' -r /etc/amvector/config.yml ']'
+ ./amvector.install
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing amvector  100%  
++ getopt -o pi --name ./setup.sh --
+ params=' --'
+ eval set -- ' --'
++ set -- --
+ true
+ case "$1" in
+ shift
+ break
+ mkdir -p /etc/amvector
+ chmod 755 /etc/amvector
+ install -m 755 -b amvector /usr/sbin/amvector
+ '[' '!' -f /etc/amvector/config.yml ']'
+ cp config.yml /etc/amvector/config.yml
+ chmod 644 /etc/amvector/config.yml
+ mkdir -p /etc/amvector/versions
+ cp -v VERSION.TXT /etc/amvector/versions
"VERSION.TXT" -> "/etc/amvector/versions/VERSION.TXT"
[root@jimv47 dm8]# amvector install
amvector: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by amvector)
amvector: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by amvector)
amvector: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by amvector)
amvector: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by amvector)
[root@jimv47 dm8]# ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
由 Roland McGrath 和 Ulrich Drepper 编写。
[root@jimv47 dm8]# cat /etc/*release
CentOS Linux release 7.9.2009 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.9.2009 (Core)
CentOS Linux release 7.9.2009 (Core)
[root@jimv47 dm8]# docker-compose -v
Docker Compose version v2.29.1
[root@jimv47 dm8]# docker -v
Docker version 26.1.3, build b72abbb
[root@jimv47 dm8]#
