### ISSUE TITLE
部署起来太麻烦了

### ISSUE THREAD

**Issue by ijkzen** [amuluze/amprobe#4]
应该在 image 内部包含默认配置，需要变动的地方通过环境变量修改，或者告知配置文件目录，用户可以映射到本地目录，重启容器后应用修改；

**Comment by amuluze** [comment]
感谢反馈，其实是有默认配置的，可按你说的这样操作，我文档写的不好，随后我更新一下发自我的 iPhone在 2024年4月27日，08:16，IJKZEN ***@***.***> 写道：﻿
应该在 image 内部包含默认配置，需要变动的地方通过环境变量修改，或者告知配置文件目录映射到本地目录，重启容器后应用修改；

**Comment by amuluze** [comment]
> 应该在 image 内部包含默认配置，需要变动的地方通过环境变量修改，或者告知配置文件目录，用户可以映射到本地目录，重启容器后应用修改；

更新了 v1.3.3 版本，同时 https://amprobedoc.amuluze.com/ 安装部署手册更新啦，简化了部署流程
