### ISSUE TITLE
系统磁盘和网卡流量监控没有数据

### ISSUE THREAD

**Issue by lixdx** [amuluze/amprobe#5]
关于网卡和磁盘这块的配置文件，配置上后数据显示异常，或者不显示。
感觉配置的没有啥问题
主机网卡和磁盘信息：
![image](https://github.com/amuluze/amprobe/assets/133653196/7b05466c-8f77-4ac3-af34-49eca896bbd9)
配置文件：
![image](https://github.com/amuluze/amprobe/assets/133653196/aac7db10-27ad-47d4-b058-ca0b3c90ed1b)

页面显示是：
<img width="1904" alt="image" src="https://github.com/amuluze/amprobe/assets/133653196/4a989a8d-76f2-4a6d-8453-e92b029190c6">

是配置有问题吗？

**Comment by amuluze** [comment]
> 关于网卡和磁盘这块的配置文件，配置上后数据显示异常，或者不显示。 感觉配置的没有啥问题 主机网卡和磁盘信息： ![image](https://private-user-images.githubusercontent.com/133653196/326184512-7b05466c-8f77-4ac3-af34-49eca896bbd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMzc1ODAsIm5iZiI6MTcxNDIzNzI4MCwicGF0aCI6Ii8xMzM2NTMxOTYvMzI2MTg0NTEyLTdiMDU0NjZjLThmNzctNGFjMy1hZjM0LTQ5ZWNhODk2YmJkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QxNzAxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzQ3YzZiZGM3ZTY0Y2Y3NmIxNTUyMTJkMGM4MTY5NGFlZTZjOGVlYjBjZTAzMDI2MzQ1N2M3MTY1ZWYyZTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TJl__Jv6Tg5I3ddu2ms8jTyFmD5q0B38i9Nheu7ydMw) 配置文件： ![image](https://private-user-images.githubusercontent.com/133653196/326184536-aac7db10-27ad-47d4-b058-ca0b3c90ed1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMzc1ODAsIm5iZiI6MTcxNDIzNzI4MCwicGF0aCI6Ii8xMzM2NTMxOTYvMzI2MTg0NTM2LWFhYzdkYjEwLTI3YWQtNDdkNC1iMDU4LWNhMGIzYzkwZWQxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QxNzAxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDc0N2Y1N2MwM2M1NDU3ZGJmOGI4MTBjODBjODNjZDU2ZDhiNDBhOGU0YzkxYWQ1M2M1YWQwMTlhMTM1NmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b8Hmd6aiPlLZDjG1BhNSFeBpOaPxVn7JJfeTEkcbZwQ)
> 
> 页面显示是： <img alt="image" width="1904" src="https://private-user-images.githubusercontent.com/133653196/326184571-4a989a8d-76f2-4a6d-8453-e92b029190c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMzc1ODAsIm5iZiI6MTcxNDIzNzI4MCwicGF0aCI6Ii8xMzM2NTMxOTYvMzI2MTg0NTcxLTRhOTg5YThkLTc2ZjItNGE2ZC04NDUzLWU5MmIwMjkxOTBjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QxNzAxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGI1ZjlhYTVjYzNmZTc5YTMyZDUyNWM5MGNiOWU3ZGU3ODc3ZDA0M2QyNmVmNzA5ZTMzYWQ2NmZlMDFhYzc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9qm33rjgrEyLK7SL4hVUHeLHP2jYhUessD-Kqh5D5jc">
> 
> 是配置有问题吗？

是个 bug，将会在 v1.3.3 中修复

**Comment by amuluze** [comment]
> 关于网卡和磁盘这块的配置文件，配置上后数据显示异常，或者不显示。 感觉配置的没有啥问题 主机网卡和磁盘信息： ![image](https://private-user-images.githubusercontent.com/133653196/326184512-7b05466c-8f77-4ac3-af34-49eca896bbd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjA5MTMsIm5iZiI6MTcxNDMyMDYxMywicGF0aCI6Ii8xMzM2NTMxOTYvMzI2MTg0NTEyLTdiMDU0NjZjLThmNzctNGFjMy1hZjM0LTQ5ZWNhODk2YmJkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNjEwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjY4YjkxNjkwNWM5OWJmNWUxNWQ5NDYxZTRiNWMxZTgxZGI2ODA4YzA1ZWM0MDY4ZTUyMTI0NzYxZTE0ZjRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j9gPeqzJYZOPRjBRD5rv1XPQWNImpixLsb-9hv_rDiw) 配置文件： ![image](https://private-user-images.githubusercontent.com/133653196/326184536-aac7db10-27ad-47d4-b058-ca0b3c90ed1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjA5MTMsIm5iZiI6MTcxNDMyMDYxMywicGF0aCI6Ii8xMzM2NTMxOTYvMzI2MTg0NTM2LWFhYzdkYjEwLTI3YWQtNDdkNC1iMDU4LWNhMGIzYzkwZWQxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNjEwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjJhOGNkZjhiZWRkODdhZmU0OTk3ZjAzNDQ2ZTg5MmJhNzNkNWIyZmMxODU4MTRmZWQwODAzZDBiNTc5ZTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.156WZtpTJGaOxzHEIJhMxyLnzSF03NwmldTQQNYFHdQ)
> 
> 页面显示是： <img alt="image" width="1904" src="https://private-user-images.githubusercontent.com/133653196/326184571-4a989a8d-76f2-4a6d-8453-e92b029190c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjA5MTMsIm5iZiI6MTcxNDMyMDYxMywicGF0aCI6Ii8xMzM2NTMxOTYvMzI2MTg0NTcxLTRhOTg5YThkLTc2ZjItNGE2ZC04NDUzLWU5MmIwMjkxOTBjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNjEwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODY2ZmVlZDFhY2Q1MzNhOWViNTMwNTYwY2Y4ZWRhMjA3MGMwMGI5MmM4N2FiZjYxNWI3NWFiNzk2ZjNmMzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9TZDA9FuhKIQmyYRjvVUW-QpVO_v8sk0xyiywiVFn6Y">
> 
> 是配置有问题吗？

v1.3.3 版本已更新，同时更新了使用手册 https://amprobedoc.amuluze.com/，对安装部署做了一些简化，可以参见文档试试新版本呀
