### ISSUE TITLE
sqplite数据库似乎没有初始化成功

### ISSUE THREAD

**Issue by coracoo** [amuluze/amprobe#6]
使用compose部署，登录的时候提示404报错，查看了一下app.log输出如下，看着是数据库没初始化成功？
![image](https://github.com/amuluze/amprobe/assets/120569020/86f830b7-7306-46e5-a6f0-b74e658322c9)

**Comment by amuluze** [comment]
> 使用compose部署，登录的时候提示404报错，查看了一下app.log输出如下，看着是数据库没初始化成功？ ![image](https://private-user-images.githubusercontent.com/120569020/326235764-86f830b7-7306-46e5-a6f0-b74e658322c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjA5NzksIm5iZiI6MTcxNDMyMDY3OSwicGF0aCI6Ii8xMjA1NjkwMjAvMzI2MjM1NzY0LTg2ZjgzMGI3LTczMDYtNDZlNS1hNmYwLWI3NGU2NTgzMjJjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxNjExMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2MyZTZiNzQwNGQwYmM2MGFjY2VkMjUyNTg1MzQ3Yjc5ZmZkNTY0ODRjMDgxYzczNjZhY2NhM2Y1NDIwODQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-cqKEaqzjPLIOnbpGm5IwlFJuY9A1xHU5DZQEjrKJ2I)

嗯嗯，看着是配置文件的问题导致后端服务初始化失败了，刚更新了 v1.3.3 版本，同时更新简化了部署手册，可以参考部署手册 https://amprobedoc.amuluze.com/ 试试新版本

**Comment by coracoo** [comment]
按照官方最新教程，配置文件应该都集成在image内了？因为外网端口没有80，所以修改了compose，将80端口映射到56781上，打开页面还是404报错。
![image](https://github.com/amuluze/amprobe/assets/120569020/5d4ff652-096a-49c8-b414-5121f9f69c01)

**Comment by amuluze** [comment]
> 按照官方最新教程，配置文件应该都集成在image内了？因为外网端口没有80，所以修改了compose，将80端口映射到56781上，打开页面还是404报错。 ![image](https://private-user-images.githubusercontent.com/120569020/326310779-5d4ff652-096a-49c8-b414-5121f9f69c01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTM2MjQsIm5iZiI6MTcxNDM1MzMyNCwicGF0aCI6Ii8xMjA1NjkwMjAvMzI2MzEwNzc5LTVkNGZmNjUyLTA5NmEtNDljOC1iNDE0LTUxMjFmOWY2OWMwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQwMTE1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGUwNzZmOGE5M2YzZGM1NDU0ZjA5NTg4MDBiZGFhMjcyOThmYjk3ZDQ3YWY5NWEzZDM2MjYyM2Y4MTM0MDI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B2WHJ2WzPY03ldP3XbuzGtoei3QFKauO9CnP0T_ngd4)
> 
> 下面是容器本身的输出信息，serve好像也有问题，我使用unraid作为宿主机。，不清楚是否和宿主机有关系？ ![image](https://private-user-images.githubusercontent.com/120569020/326311010-58a3c6d7-143c-418a-888d-098bfc29a3e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTM2MjQsIm5iZiI6MTcxNDM1MzMyNCwicGF0aCI6Ii8xMjA1NjkwMjAvMzI2MzExMDEwLTU4YTNjNmQ3LTE0M2MtNDE4YS04ODhkLTA5OGJmYzI5YTNlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQwMTE1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTNmODI1ZjUxOGY1YmQwMmZjN2UxMzliNjdhOGQyMTEwYmVmZThlNzA2NDQ1MTNjNzdhNTgxY2NhZTZmYjEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BNMHU9D7I2In_ybrVUwFPOoIzts1HMDgTOtR-WY3aUg)

修改 nginx 的配置文件中的端口配置然后挂载进去覆盖默认的nginx 配置，不是改 compose 中的配置

```nginx
worker_processes  1;
daemon off;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;     #### 修改这里的默认端口
        #server_name  amprobe.amuluze.com; # 服务器地址或绑定域名

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            rewrite ^/api/(.*)$ /$1 break;  #必须的写这个，使用nginx的rewrite对uri进行重写  下面这行也要改为api
            proxy_pass http://127.0.0.1:8000/; #跨域转发路由地址
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /ws/ {
            # rewrite ^/wsUrl/(.*)$ /$1 break; #拦截标识去除
            proxy_pass http://127.0.0.1:8000/ws/;

            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # 错误页配置
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}

```

```yml
version: '3'
services:
    amprobe:
        image: amuluze/amprobe:v1.3.3
        container_name: amprobe
        restart: always
        network_mode: "host"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /dev:/host/dev:ro
            - /data/amprobe/nginx/nginx.conf:/etc/nginx/nginx.conf
```

**Comment by coracoo** [comment]
感谢答复，最后发现问题在于unraid的问题，同样的配置在群晖等主机上可顺利运行，但是在unraid上，后台报错都是无法找到database文件，我给予了privileged依旧无效，后续会在unraid上尝试使用其它数据库。

**Comment by amuluze** [comment]
> 感谢答复，最后发现问题在于unraid的问题，同样的配置在群晖等主机上可顺利运行，但是在unraid上，后台报错都是无法找到database文件，我给予了privileged依旧无效，后续会在unraid上尝试使用其它数据库。

如果是非 root 用户，将 /data/amprobe 目录 改到根目录下试试 比如 /home/ubuntu/amprobe，之前碰到过在 vps 中配置文件挂载失败的问题
